import { UserController } from './controller/UserController';
import { InventoryController } from './controller/InventoryController';

export const Routes = [{
    method: 'get',
    route: '/api/users',
    controller: UserController,
    action: 'all'
}, {
    method: 'get',
    route: '/api/users/:id',
    controller: UserController, 
    action: 'one'
}, {
    method: 'post',
    route: '/api/users',
    controller: UserController,
    action: 'save'
}, {
    method: 'post',
    route: '/api/login',
    controller: UserController,
    action: 'login'
}, {
    method: 'post',
    route: '/api/register',
    controller: UserController,
    action: 'register'
}, {
    method: 'delete',
    route: '/api/users/:id',
    controller: UserController,
    action: 'remove'
}, {
    method: 'get',
    route: '/api/categories',
    controller: InventoryController,
    action: 'categories'
}, {
    method: 'get',
    route: '/api/categories/:id',
    controller: InventoryController,
    action: 'getCategory'
}, {
    method: 'post',
    route: '/api/categories',
    controller: InventoryController,
    action: 'addCategory'
}, {
    method: 'delete',
    route: '/api/categories/:id',
    controller: InventoryController,
    action: 'removeCategory'
}, {
    method: 'get',
    route: '/api/products',
    controller: InventoryController,
    action: 'products'
}, {
    method: 'get',
    route: '/api/products/:id',
    controller: InventoryController,
    action: 'getProduct'
}, {
    method: 'post',
    route: '/api/products',
    controller: InventoryController,
    action: 'addProduct'
}, {
    method: 'delete',
    route: '/api/products/:id',
    controller: InventoryController,
    action: 'removeProduct'
}, {
    method: 'get',
    route: '/api/catalogue',
    controller: InventoryController,
    action: 'catalogue'
}, {
    method: 'post',
    route: '/api/order',
    controller: InventoryController,
    action: 'order'
}, {
    method: 'post',
    route: '/api/purchase',
    controller: InventoryController,
    action: 'purchase'
}, {
    method: 'get',
    route: '/api/discounts',
    controller: InventoryController,
    action: 'discounts'
}];
